# Generated by Django 5.2.5 on 2025-08-29 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_alter_question_options_alter_quiz_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="selected_choice_ids",
        ),
        migrations.AlterField(
            model_name="answer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizzes.submission"
            ),
        ),
    ]
