# Generated by Django 5.2.5 on 2025-08-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_remove_answer_selected_choice_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="selected_choices",
            field=models.ManyToManyField(to="quizzes.choice"),
        ),
    ]
